### ISSUE TITLE
Ways to determine if camera is ON or OFF?

### ISSUE THREAD

**Issue by sguillemette123** [Blackdread/canon-sdk-java#100]
Hello,

Sorry for asking questions here but support is rather limited for the EDSDK. I have searched everywhere and i couldn't see anything.  By any chance, do you know if there is a way to determine if camera is ON or OFF? I mean is there an event or something that i can rely on to determine if the camera been disconnected? Because the method GetAllConnectedCamera will still return the camera even if its not available (unplugged for example). 

Thanks for your help! That would be my last question.

**Comment by Blackdread** [comment]
Have a look in events of CanonCamera class (within "public class Event {...}")

You also have the "isConnected" command but better to not use it too often, timeout may be long as well.
