### ISSUE TITLE
GUI - where can I find this (Software example using this Framework/SDK)

### ISSUE THREAD

**Issue by rider87** [Blackdread/canon-sdk-java#161]
Hi, 

where can I find a Main class for the GUI which I can see under:
"Software example using this Framework/SDK"

Thanks

**Comment by Blackdread** [comment]
This is private software.

**Comment by rider87** [comment]
ok, why not share it? Seems like also other people are interested?

**Comment by Blackdread** [comment]
Software code can be bought but mostly consultancy is provided to companies

**Comment by rider87** [comment]
And where can someone buy it?

**Comment by Blackdread** [comment]
This is a minimum two zeros amount, this is part of a demo for companies and can be more expensive if spend some in-person/video call demo and explanation of framework

**Comment by rider87** [comment]
I need just a simple GUI like this where you can configure those things and take photo.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/9787533/181585466-110f47a0-7ce5-40bc-bf5b-fdccf9bef146.png">

**Comment by Blackdread** [comment]
Yes can, only time is required, which companies usually pay

**Comment by rider87** [comment]
I´m not a company... It´s just a free time project :) 
What do you mean with "time is required" ?

**Comment by Blackdread** [comment]
It takes time write code to do what you want.
I can provide services for companies, obviously paid.

**Comment by rider87** [comment]
yes, I agree. 
But I´m still don´t know, why there is a screenshot postet in the readme and this cannot be found here as example.
I saw also other people asked for that already. Therefore why not just share that, would be helpful for all people ;)
