### ISSUE TITLE
Path can be customized in CanonLibraryImpl?

### ISSUE THREAD

**Issue by rider87** [Blackdread/canon-sdk-java#163]
Hi,

I would like to know how can I customize the path?
Which kind of code do I need to set it to a specific path?

On the other hand I understood it also, that I can place the whole EDSDK / EDSDK64 folder in the "Ressource" folder from the Java project and it will be recognized automatically?

Thanks,

**Comment by Blackdread** [comment]
Read https://github.com/Blackdread/canon-sdk-java/blob/master/camera-framework/README.md

**Comment by rider87** [comment]
"Path can be customized in [CanonLibraryImpl] "?

I read this.. But how? Which setter?
