### ISSUE TITLE
Use the lib for MacOS?

### ISSUE THREAD

**Issue by rider87** [Blackdread/canon-sdk-java#164]
Hi, 

I´m developing on MacOs and not Windows. Therefore I would need it also for MacOS.

The path / files seems like is not the same as in Windows? 
Is this an issue?

<img width="371" alt="image" src="https://user-images.githubusercontent.com/9787533/181847305-847adda7-9743-4a58-bf1a-32c4c20dbdb6.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/9787533/181847333-04820bb8-52c0-4ddd-8fa0-43a5a2004c76.png">

What needs to be changed to use it for MacOS?
Thanks

**Comment by Blackdread** [comment]
https://github.com/Blackdread/canon-sdk-java/blob/master/camera-framework/README.md

**Comment by rider87** [comment]
sorry, but I cannot find any answer here about my question
