### ISSUE TITLE
Path change for DLL etc.?

### ISSUE THREAD

**Issue by testing138** [Blackdread/canon-sdk-java#165]
Hi,

In your readme is written I can change the path:

<img width="969" alt="image" src="https://user-images.githubusercontent.com/52133436/182348143-8a469720-2930-4fca-bf06-1a33aefe3453.png">

Can you let me know how can I change this via code example?
I would like to have the files in 

src/main/resources/Camera/Canon/Windows/**EDSDK**
src/main/resources/Camera/Canon/Windows/**EDSDK_64**

Thank you

**Comment by Blackdread** [comment]
EDSDK is proprietary of Canon, you need to get it yourself

**Comment by testing138** [comment]
I´m sorry, but it´s not clear enough for me.

I can see from the readme:
![grafik](https://user-images.githubusercontent.com/52133436/182562324-67a6c224-1f83-4706-8c67-98713631996d.png)


If I have a look into the CanonLibraryImpl:
https://github.com/Blackdread/canon-sdk-java/blob/master/camera-framework/src/main/java/org/blackdread/cameraframework/api/helper/factory/CanonLibraryImpl.java

How can I see it to another path, e.g. C:/temp ?

How can I do something like:
```
EdsdkLibrary EDSDK = new EdsdkLibrary ();
EDSDK.setPath("C://temp);
```

**Comment by Blackdread** [comment]
You found the `CanonLibraryImpl` class, everything is in it to understand how to customize the path.

**Comment by rider87** [comment]
Hi Yoann,
I have the same question and I don´t understand how we can set the path, because there is also **no Setter** in the `CanonLibraryImpl `.
So please be so kind and let us know how we can do this.

Thanks.
