### ISSUE TITLE
shoot.shoot() -> get an Stream not a file?

### ISSUE THREAD

**Issue by testing138** [Blackdread/canon-sdk-java#167]
I see the following code will take a picture:

```
Shoot shoot = camera.getShoot();
List<File> file = shoot.shoot();
```

Currently the picture is saved in a temp folder.
Is there also a possibility to get only a OutputStream? 
Or do I need to get an outputstream from the file and delete the file afterwards? (not the best for performance!)

Any ideas?

**Comment by Blackdread** [comment]
You can code your own commands

**Comment by Blackdread** [comment]
same feature as https://github.com/Blackdread/canon-sdk-java/issues/1
