### ISSUE TITLE
Live View -> any example?

### ISSUE THREAD

**Issue by testing138** [Blackdread/canon-sdk-java#168]
Hi, 

I would like to enable the live view in my GUI.

I want to do:
- Get live view
- Send Stream / Image to my JSF Controller
- Output Image as Stream

How can I do this... any examples etc.?
How does this general technically works? Do I have to send many images to my JSF Controller etc.?

Thanks for any help

**Comment by Blackdread** [comment]
There is code example, this is not stackoverflow
