### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Ahmednagyyy** [Blackdread/canon-sdk-java#26]
Can I use it for android app ?

**Comment by Blackdread** [comment]
I would say no but you can try.
Canon provide .dll, .lib and mac lib

**Comment by Ahmednagyyy** [comment]
> I would say no but you can try.
> Canon provide .dll, .lib and mac lib

I'll try and post here for any updates, but is there any documentation for the sdk ( classes, functions, etc.. ) ?

**Comment by Blackdread** [comment]
For documentation of java code -> everything has javadoc so quite clear.
The sdk given on Canon website, they provide a pdf with each functions usage etc

**Comment by Ahmednagyyy** [comment]
Thank you

**Comment by sops21** [comment]
@Ahmednagyyy where you able to get this running on android?
