### ISSUE TITLE
[REQUEST] SDK copy

### ISSUE THREAD

**Issue by sidetraxaudio** [Blackdread/canon-sdk-java#268]
Hi. 
Can someone please help me with copy of the sdk. I want to have a play to see if I can contribute. 
I'm in Australia and despite there being no link on the Oceania site to actually apply, Oceania Canon is the most useless arm in the whole company anyway. If they even did have a link nobody would reply. It's always been like this from development to camera firmware.

If anyone can help me that would be great. Thanks.

**Comment by Blackdread** [comment]
Hey, sorry I cannot provide a copy of the SDK from Canon.
You have to obtain it yourself, that's part of their licensing, you can get it for free.
