### ISSUE TITLE
EDSDK - Request Autofocus without stopping liveview image retrieval

### ISSUE THREAD

**Issue by AndreasCottet** [Blackdread/canon-sdk-java#269]
Hello everyone,

Thank you for this very useful library.

I have a question concerning only the EDSDK.

I'd like to be able to autofocus while retrieving images from the liveview.

In my case, when I autofocus, image retrieval stops and starts again once I've received the autofocus command. 
I use the :
SendCommand(kEdsCameraCommand_PressShutterButton, kEdsCameraCommand_ShutterButton_Halfway) ;
Is this possible? This function is available via Canon's EOS Utility application.

Thank you for taking the time to read this document.

**Comment by Blackdread** [comment]
Hey, I am not sure if it is possible.
I have not tested, you would need to try it or read documentation of EDSDK.

I close this issue as it seems to be a question more than a feature request.
If there is an implementation needed not already existing with all commands that this java SDK provides, then you can make a PR.
