### ISSUE TITLE
Send Command Into Camera (Improve Docs Request)

### ISSUE THREAD

**Issue by Megnatis** [Blackdread/canon-sdk-java#297]
Hello, I can't find anywhere or my bad search that can find how to set camera settings and send it to camera , In example How can I set SaveInto to Both or PC ? or change ImageSize?

**Comment by Blackdread** [comment]
Sorry, this is part of the code and Canon SDK documentation.
I provided the library, I do not do support for this kind of things

**Comment by Megnatis** [comment]
So it mean Command of set like ISO set or SaveInto Is not applied into the sdk? and warper code that you added? or I miss something?

**Comment by Blackdread** [comment]
I meant I do not provide help/support unless for consultancy work.
Everything is in the code, if missing then it can easily be added via new commands.
