### ISSUE TITLE
CameraRef is null

### ISSUE THREAD

**Issue by skit4214** [Blackdread/canon-sdk-java#3]
Hi,

Try to start use this wrapper, but have some problems on start
I use code from demo and always get "CameraRef is null" exeption in camera.openSession() method 
If use CameraManager.getAllCameras().get(0) it's ok and i get my camera (but it some others issues in demo code for me)
If use new CanonCamera() in edsdk4j it's ok and i get my camera.

Thank you
 
```
void tryOne() {
        cameraAddedListener = event -> {
           log.info("Camera added detected: {}", event);
        };
        cameraObjectListener = event -> {
            log.info("Object event: {}", event);
        };
        cameraPropertyListener = event -> {
            log.info("Property event: {}", event);
        };
        cameraStateListener = event -> {
            log.info("State event: {}", event);
        };
        
        new FrameworkInitialisation()
                .registerCameraAddedEvent()
                .withEventFetcherLogic()
                .withCameraAddedListener(cameraAddedListener)
                .initialize();

        final CanonCamera camera = new CanonCamera();  //camera have empty props     
        final EdsdkLibrary.EdsCameraRef edsCameraRef = get(camera.openSession());
        // ...
}
```

> Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: CameraRef is null
> 	at org.blackdread.cameraframework.api.camera.CanonCamera.lambda$getCameraRefInternal$0(CanonCamera.java:149)
> 	at java.util.Optional.orElseThrow(Optional.java:290)
> 	at org.blackdread.cameraframework.api.camera.CanonCamera.getCameraRefInternal(CanonCamera.java:149)
> 	at org.blackdread.cameraframework.api.camera.CanonCamera.dispatchCommand(CanonCamera.java:133)
> 	at org.blackdread.cameraframework.api.camera.CanonCamera.openSession(CanonCamera.java:286)
> 	at pdcanoncamera.PDCanonCamera.tryOne(PDCanonCamera.java:182)

camera-framework 1.1.1
EDSDK 3.9.0
win10 (x64)

**Comment by Blackdread** [comment]
Indeed I see the issue, I will fix.

The issue is I try to get the cameraRef when dispatching the command to open the session
```
public <T extends CanonCommand<R>, R> T dispatchCommand(T command) {
        command = applyTarget(command);
        command = applyExtraOptions(command);
        command = applyDefaultCommandDecoration(command);
        CanonFactory.commandDispatcher().scheduleCommand(getCameraRefInternal(), command);
        return command;
}
```

The best is to use CameraManager class as it does not have this issue, it handles the session automatically and will set the cameraRef field once retrieved

Unfortunately I could not have automatic test for that part of the code.
